name: Approval
on: 
  - workflow_call
  - workflow_dispatch
jobs: 
  approval_and_notification:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
     - name: checkout the code
       uses: actions/checkout@v5.0.0
     - name: send notification to slack
       uses: slackapi/slack-github-action@v2.1.1
       with:
        payload: '{"text":"Deployment started!"}'
        webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
       
  
